-- XW User-Tables 0.1

     CREATE TABLE XW_USERS (
         USER_ID int(11) NOT NULL AUTO_INCREMENT,
         USER_NAME VARCHAR(255) NOT NULL,
         USER_PASSWORD VARCHAR(255) NOT NULL,
         USER_EMAIL VARCHAR(255) NOT NULL,
         USER_ACTIVE int(1) DEFAULT 1,
         USER_PMPOPUP int(1) DEFAULT 0,
         PRIMARY KEY  (USER_ID),
         UNIQUE (USER_NAME)
     )   ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
     
     -- begin 0.3
     ALTER TABLE XW_USERS ADD COLUMN(USER_REGISTRATIONDATE DATETIME);    
     
     UPDATE XW_USERS SET
       USER_REGISTRATIONDATE=CURRENT_TIMESTAMP
     WHERE USER_REGISTRATIONDATE IS NULL;  
     
     -- end
     
     INSERT INTO XW_USERS(USER_NAME,USER_PASSWORD, USER_EMAIL, USER_REGISTRATIONDATE,USER_ACTIVE) VALUES ('admin',md5('admin'),'admin@localhost', CURRENT_TIMESTAMP,1);

     CREATE TABLE XW_GROUPS (
         GROUP_ID int(11) NOT NULL AUTO_INCREMENT,
         GROUP_NAME varchar(255) NOT NULL UNIQUE,
         GROUP_DESCRIPTION varchar(255),
         PRIMARY KEY  (GROUP_ID)
     )   ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
     
     INSERT INTO XW_GROUPS(GROUP_NAME,GROUP_DESCRIPTION) VALUES ('admins','DO NOT DELETE - global Administrartor');
     -- 0.3
     INSERT INTO XW_GROUPS(GROUP_NAME, GROUP_DESCRIPTION) VALUES ('pagesAdmins','Administrators for pages tasks.');
     INSERT INTO XW_GROUPS(GROUP_NAME, GROUP_DESCRIPTION) VALUES ('instanceAdmins','Administrators for instance tasks (also themes).');
     -- end 0.3 

     CREATE TABLE XW_USERS_GROUPS (
         GROUP_ID int(11) NOT NULL,
         USER_ID int(11) NOT NULL,
         PRIMARY KEY  (GROUP_ID,USER_ID)
     )   ENGINE=MyISAM DEFAULT CHARSET=latin1;
     
     INSERT INTO XW_USERS_GROUPS(GROUP_ID,USER_ID) VALUES (1,1);
     
     -- 0.3.6
		
		CREATE TABLE XW_USERDEFINEDGROUPS(
		    USERDEFINEDGROUP_ID INT(11) NOT NULL AUTO_INCREMENT,
		    USERDEFINEDGROUP_NAME VARCHAR(255) NOT NULL,
		    PRIMARY KEY (USERDEFINEDGROUP_ID)
		)   ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
		
		CREATE TABLE XW_CREATORS_USERDEFINEDGROUPS(
		    USERDEFINEDGROUP_ID INT(11) NOT NULL,
		    USER_ID INT(11) NOT NULL,
		    PRIMARY KEY(USER_ID, USERDEFINEDGROUP_ID)
		)   ENGINE=MyISAM DEFAULT CHARSET=latin1;
		
		CREATE TABLE XW_USERS_USERDEFINEDGROUPS(
		    USERDEFINEDGROUP_ID int(11) NOT NULL,
		    USER_ID INT(11) NOT NULL,
		    PRIMARY KEY(USER_ID, USERDEFINEDGROUP_ID)
		)   ENGINE=MyISAM DEFAULT CHARSET=latin1;

     -- end 0.3.6

-- XW Private Message Tables 0.1

     CREATE TABLE XW_MSGS (
         MSG_ID int(11) NOT NULL AUTO_INCREMENT,
         MSG_TO int(11) NOT NULL,
         MSG_FROM int(11) NOT NULL,
         MSG_CONTENT text NOT NULL,
         MSG_HEADER varchar(255) default NULL,
         MSG_DATE datetime NOT NULL,
         MSG_VIEWED int(1) NOT NULL default '0',
         PRIMARY KEY  (`MSG_ID`)
     )   ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
     
     -- aoop 0.3 update 0.3
     ALTER TABLE XW_MSGS ADD COLUMN (MSG_DELETED int(1) DEFAULT 0);
     -- aoop 0.3.4 update 0.3
     ALTER TABLE XW_MSGS ADD COLUMN (MSG_TITLE VARCHAR(255) DEFAULT "new message");

-- XW Friends 0.1

     CREATE TABLE XW_FRIENDS (
         USER_ID int(11) NOT NULL,
         FRIEND_ID int(11) NOT NULL,
         PRIMARY KEY  (USER_ID,FRIEND_ID)
     )   ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- XW UserInfos 0.1

     CREATE TABLE XW_USERS_USERINFOS (
         USER_ID int(11) NOT NULL,
         USERINFO_ID int(11) NOT NULL,
         PRIMARY KEY  (USER_ID,USERINFO_ID)
     )   ENGINE=MyISAM DEFAULT CHARSET=latin1;

     CREATE TABLE XW_USERINFOS (
         USERINFO_ID int(11) NOT NULL AUTO_INCREMENT,
         USERINFO_INFO text collate latin1_general_ci,
         USERINFO_ICQ varchar(255) collate latin1_general_ci,
         USERINFO_MSN varchar(255) collate latin1_general_ci,
         USERINFO_HOMEPAGE varchar(255) collate latin1_general_ci,
         USERINFO_SEX varchar(255) collate latin1_general_ci,
         USERINFO_SINGLE varchar(255) collate latin1_general_ci,
         USERINFO_LOCATION varchar(255) collate latin1_general_ci,
         USERINFO_AGE varchar(255) collate latin1_general_ci,
         PRIMARY KEY  (USERINFO_ID)
     )   ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
     
    -- 0.3.4
CREATE TABLE XW_USERPROFILEITEMS(
  USERPROFILEITEM_ID INT(11) NOT NULL AUTO_INCREMENT,
  USERPROFILEITEM_NAME VARCHAR(255) NOT NULL,
  USERPROFILEITEM_VALUE VARCHAR(255) DEFAULT '',
  USERPROFILEITEM_CHANGEDATE DATETIME,
  PRIMARY KEY(USERPROFILEITEM_ID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

   -- 0.3.6
   ALTER TABLE XW_USERPROFILEITEMS ADD COLUMN (USERPROFILEITEM_ONLYFRIENDS INT(1) DEFAULT 0);
   ALTER TABLE XW_USERPROFILEITEMS ADD COLUMN (USERPROFILEITEM_DATAFORMAT VARCHAR(25) DEFAULT 'string');
   --

CREATE TABLE XW_USERS_USERPROFILEITEMS(
  USER_ID INT(11) NOT NULL,
  USERPROFILEITEM_ID INT(11) NOT NULL,
  PRIMARY KEY (USER_ID,USERPROFILEITEM_ID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
     -- end 0.3.4 
     
-- XW Photos 0.1

     CREATE TABLE XW_PHOTOS (
         PHOTO_ID int(11) NOT NULL AUTO_INCREMENT,
         PHOTO_PATH varchar(255) NOT NULL,
         PHOTO_DATE datetime NOT NULL,
         PHOTO_FRIENDS INT(1) DEFAULT 0,
         PRIMARY KEY (PHOTO_ID)
     )   ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
     
     ALTER TABLE XW_PHOTOS ADD COLUMN (PHOTO_DRAFT INT(1) DEFAULT 0); -- 0.3.5
	 ALTER TABLE XW_PHOTOS ADD COLUMN (PHOTO_TITLE VARCHAR(255) DEFAULT 'photo'); -- 0.3.5

     CREATE TABLE XW_USERS_PHOTOS(
         USER_ID int(11) NOT NULL,
         PHOTO_ID int(11) NOT NULL,
         PRIMARY KEY (USER_ID,PHOTO_ID)
     )   ENGINE=MyISAM DEFAULT CHARSET=latin1;   
     
     
-- XW FileTypes 0.3

CREATE TABLE XW_FILETYPEDEFINITIONS(
    FILETYPEDEFINITION_ID int(11) NOT NULL AUTO_INCREMENT,
    FILETYPEDEFINITION_NAME VARCHAR(255),
    FILETYPEDEFINITION_PATTERN VARCHAR(255),
    PRIMARY KEY (FILETYPEDEFINITION_ID)
)   ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE XW_FILETYPEPROFILES(
    FILETYPEPROFILE_ID int(11) NOT NULL AUTO_INCREMENT,
    FILETYPEPROFILE_NAME VARCHAR(255),
    FILETYPEPROFILE_DESCRIPTION VARCHAR(255),
    PRIMARY KEY (FILETYPEPROFILE_ID)
)   ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE XW_FILETYPEPROFILES_FILETYPEDEFINITIONS(
    FILETYPEDEFINITION_ID int(11) NOT NULL,
    FILETYPEPROFILE_ID int(11) NOT NULL,
    PRIMARY KEY (FILETYPEDEFINITION_ID,FILETYPEPROFILE_ID)
)   ENGINE=MyISAM DEFAULT CHARSET=latin1;   

-- XW Comments 0.3.4

CREATE TABLE XW_COMMENTS(
  COMMENT_ID INT(11) NOT NULL AUTO_INCREMENT,
  COMMENT_PARENTCODE VARCHAR(255) NOT NULL,
  COMMENT_DATE DATETIME,
  COMMENT_TEXT TEXT NOT NULL,
  PRIMARY KEY(COMMENT_ID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE XW_USERS_COMMENTS(
  USER_ID INT(11) NOT NULL,
  COMMENT_ID INT(11) NOT NULL,
  PRIMARY KEY (USER_ID,COMMENT_ID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;    

-- XW Login-Protocol 0.4.1

CREATE TABLE XW_LOGINLOGS(
	LOGINLOG_ID INT(11) NOT NULL AUTO_INCREMENT,
	LOGINLOG_IP VARCHAR(25) NOT NULL,
	LOGINLOG_DATE DATETIME NOT NULL,
	PRIMARY KEY (LOGINLOG_ID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE XW_USERS_LOGINLOGS(
  USER_ID INT(11) NOT NULL,
  LOGINLOG_ID INT(11) NOT NULL,
  PRIMARY KEY (USER_ID,LOGINLOG_ID)
) ENGINE=MyISAM DEFAULT CHARSET=latin1; 

ALTER TABLE XW_USERS ADD COLUMN USER_USELOGINLOG INT(1) DEFAULT 0; 

-- aoop 0_4_1 remove md5 and user more secured passwords

ALTER TABLE XW_USERS ADD COLUMN USER_USESHIGHSECPASSWORD INT(1) DEFAULT 0;
